<?php

namespace ApidaeBundle\Repository;
use ApidaeBundle\Entity\Categorie;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {
    private $em;

    public function getCategoriesHebergements() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catRefType = ?1')
            ->orWhere('c.catRefType = ?2')
            ->orWhere('c.catRefType = ?3')
            ->orWhere('c.catRefType = ?4')
            ->setParameters(array(1 => 'HebergementCollectifType', 2 => 'HebergementLocatifType',
                3 => 'HotelleriePleinAirType', 4 => 'HotellerieType'));
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getCategoriesRestaurants() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catRefType = ?1')
            ->setParameter(1,'RestaurationCategorie' );
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getCategoriesActivites() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catRefType = ?1')
            ->orWhere('c.catRefType = ?2')
            ->orWhere('c.catRefType = ?3')
            ->setParameters(array(1 => 'PatrimoineCulturelType', 2 => 'ActiviteCategorie',
                3 => 'ActiviteType'));
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getCategoriesEvenements() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catRefType = ?1')
            ->setParameter(1,'FeteEtManifestationType' );
        $query = $qb->getQuery();
        return $query->getResult();
    }


}
