<?php

namespace ApidaeBundle\Repository;

/**
 * DureeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DureeRepository extends \Doctrine\ORM\EntityRepository
{
}
