<?php

namespace ApidaeBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository {

    //TODO
    public function getAjourdhui() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('e')
            ->from('ApidaeBundle:Evenement', 'e')
            ->where('o.ouvDateDebut = ?1')
            ->setParameters(array(1 => new DateTime()));
        $query = $qb->getQuery();
        return $query->getResult();
    }

    //TODO
    public function getSemaine() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catId = ?1')
            ->orWhere('c.catId = ?2')
            ->setParameters(array(1 => '2734', 2 => '2736'));
        $query = $qb->getQuery();
        return $query->getResult();
    }

    //TODO
    public function getTrenteJours() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('ApidaeBundle:Categorie', 'c')
            ->where('c.catId = ?1')
            ->orWhere('c.catId = ?2')
            ->setParameters(array(1 => '2734', 2 => '2736'));
        $query = $qb->getQuery();
        return $query->getResult();
    }

}
