<?php

namespace ApidaeBundle\Repository;

/**
 * HebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementRepository extends ObjetApidaeRepository
{
}
