<?php

namespace ApidaeBundle\Repository;

/**
 * InformationsTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationsTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
