<?php

namespace ApidaeBundle\Repository;

/**
 * LabelQualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelQualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
