<?php

namespace ApidaeBundle\Repository;

/**
 * MoyenCommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenCommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
