<?php

namespace ApidaeBundle\Repository;

/**
 * ObjetLieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetLieRepository extends \Doctrine\ORM\EntityRepository
{
}
