<?php

namespace ApidaeBundle\Repository;
use ApidaeBundle\Entity\ObjetApidae;

/**
 * ObjetApidaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetApidaeRepository extends \Doctrine\ORM\EntityRepository {

    public function getObjetByCategorie() {
        //TODO getObjetByCategorie
    }

    public function getObjetByService() {
        //TODO getObjetByService
    }

    public function getObjetByNom($chaine) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('o')
            ->from('ApidaeBundle:ObjetApidae', 'o')
            ->where($qb->expr()->like('o.nom', ':chaine'))
            ->setParameter('chaine','%'.$chaine.'%' );
        $query = $qb->getQuery();
        return $query->getResult();
    }

}
