<?php

namespace ApidaeBundle\Repository;
use DateTime;

/**
 * OuvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvertureRepository extends \Doctrine\ORM\EntityRepository
{

    //TODO
    public function getAjourdhui()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('e')
            ->from('ApidaeBundle:Evenement', 'e')
            ->where('o.ouvDateDebut = ?1')
            ->setParameters(array(1 => new DateTime()));
        $query = $qb->getQuery();
        return $query->getResult();

    }

}
