<?php

namespace ApidaeBundle\Repository;
use DateTime;

/**
 * OuvertureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvertureRepository extends \Doctrine\ORM\EntityRepository
{
}
