<?php

namespace ApidaeBundle\Repository;

/**
 * SejourPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
