<?php

namespace ApidaeBundle\Repository;

/**
 * SelectionApidaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectionApidaeRepository extends \Doctrine\ORM\EntityRepository
{
}
