<?php

namespace ApidaeBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Renvoie les objets affiliés à une liste de servcies donnée.
     * @param $ids
     * @return array
     */
    public function getObjetsByids($ids) {
        return $this->createQueryBuilder('s')
            ->where('s.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult();
    }


    /**
     * Nombre de services étant affiliés à la liste d'objet Apidae donnée
     * @param $idsObjets
     * @param $idsServices
     * @return array
     */
    public function getCountServicesByIdsObjets($idsServices, $idsObjets) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('o')
            ->from('ApidaeBundle:ObjetApidae', 'o')
            ->innerJoin('o.services', 's')
            ->where('s.serId IN (?1)')
            ->andWhere('o.idObj IN (?2)')
            ->groupBy('o.idObj')
            ->setParameters(array(1 => $idsServices, 2 => $idsObjets));
        $query = $qb->getQuery()->getResult();
        return count($query);
    }

}
