<?php

namespace ApidaeBundle\Repository;

/**
 * TraductionObjetApidaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraductionObjetApidaeRepository extends \Doctrine\ORM\EntityRepository
{

}
