<?php

namespace ApidaeBundle\Repository;

/**
 * TypePublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePublicRepository extends \Doctrine\ORM\EntityRepository
{
}
