user:
    resource: "@UserBundle/Controller/"
    type:     annotation

userBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix : /{_locale}/
    requirements:
       _locale: en|fr


ApidaeBundle:
    resource: "@ApidaeBundle/Resources/config/routing.yml"
    prefix : /{_locale}/
    requirements:
        _locale: en|fr
