user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

userBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix : /

ApidaeBundle:
    resource: "@ApidaeBundle/Resources/config/routing.yml"
    prefix : /{_locale}/
    requirements:
        _locale: en|fr
