apidae:
    path : /
    defaults :  { _controller: ApidaeBundle:Default:index }
    prefix : /

test:
    path : /test
    defaults: { _controller: ApidaeBundle:Index:index }

traitement:
    path: /traitement
    defaults: { _controller: ApidaeBundle:Traitement:traitement }
