user:
    resource: "@UserBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

userBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix : /{_locale}/
    requirements:
       _locale: en|fr


ApidaeBundle:
    resource: "@ApidaeBundle/Resources/config/routing.yml"
    prefix : /{_locale}/
    requirements:
        _locale: en|fr

index:
    path : /
    defaults: { _controller: ApidaeBundle:Default:index }