user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /accueil

apidae:
    path : /{langueLocale}/
    defaults :  { _controller: ApidaeBundle:Default:index }
    prefix : /

userBundle:
    resource: "@UserBundle/Resources/config/routing.yml"

ApidaeBundle:
    resource: "@ApidaeBundle/Resources/config/routing.yml"

