index:
    path : /accueil
    defaults: { _controller: ApidaeBundle:Default:index }

traitement:
    path: /traitement
    defaults: { _controller: ApidaeBundle:Traitement:traitement }

liste:
    path: /{typeObjet}/{categorieId}-{libelleCategorie}
    defaults: { _controller: ApidaeBundle:Default:liste }

offre:
    path: offre/{id}
    defaults: { _controller: ApidaeBundle:Default:offre }

listeEvenement:
    path: /listeEvenements/{periode}-jours
    defaults: { _controller: ApidaeBundle:Default:listeEvenements }

panier:
    path: /panier
    defaults: { _controller: UserBundle:Default:voirPanier }

gestionOffres:
    path: /admin/gestion/offres/
    defaults: { _controller: ApidaeBundle:GestionOffre:gestionOffres }
    methods: [POST, GET]

modifierOffre:
    path: /admin/modifier/offre/{offreId}
    defaults: { _controller: ApidaeBundle:GestionOffre:modifierOffre }

rechercheAffinnee:
    path: /recherche/{typeObjet}
    defaults: { _controller: ApidaeBundle:Default:rechercheAffinnee }

rechercheSimple:
    path: /recherche
    defaults: { _controller: ApidaeBundle:Default:rechercheSimple }

