index:
    path : /accueil
    defaults: { _controller: ApidaeBundle:Default:index }

traitement:
    path: /traitement
    defaults: { _controller: ApidaeBundle:Traitement:traitement }

offre:
    path: /offre/{id}
    defaults: { _controller: ApidaeBundle:Default:offre }

liste:
    path: /liste/{typeObjet}/{categorieId}
    defaults: { _controller: ApidaeBundle:Default:liste }

listeEvenement:
    path: /listeEvenements/{periode}
    defaults: { _controller: ApidaeBundle:Default:listeEvenements }

panier:
    path: /panier
    defaults: { _controller: UserBundle:Default:voirPanier }

gestionOffres:
    path: /admin/gestion/offres/
    defaults: { _controller: ApidaeBundle:GestionOffre:gestionOffres }
    methods: [POST, GET]

modifierOffre:
    path: /admin/modifier/offre/{offreId}
    defaults: { _controller: ApidaeBundle:GestionOffre:modifierOffre }

