index:
    path : /{langueLocale}/accueil
    defaults: { _controller: ApidaeBundle:Default:index }

traitement:
    path: /traitement
    defaults: { _controller: ApidaeBundle:Traitement:traitement }

offre:
    path: /{langueLocale}/offre/{id}
    defaults: { _controller: ApidaeBundle:Default:offre }

listeEvenement:
    path: /{langueLocale}/listeEvenements/{periode}-jours
    defaults: { _controller: ApidaeBundle:Default:listeEvenements }

liste:
    path: /{langueLocale}/{typeObjet}/{categorieId}-{libelleCategorie}
    defaults: { _controller: ApidaeBundle:Default:liste }

panier:
    path: /{langueLocale}/panier
    defaults: { _controller: UserBundle:Default:voirPanier }

gestionOffres:
    path: /{langueLocale}/admin/gestion/offres/
    defaults: { _controller: ApidaeBundle:GestionOffre:gestionOffres }
    methods: [POST, GET]

modifierOffre:
    path: /{langueLocale}/admin/modifier/offre/{offreId}
    defaults: { _controller: ApidaeBundle:GestionOffre:modifierOffre }

rechercheAffinnee:
    path: /recuperationJson/{categorieId}/{typeObjet}
    defaults: { _controller: ApidaeBundle:Default:rechercheAffinnee }
    methods: [POST, GET]

rechercheSimple:
    path: /{langueLocale}/recherche
    defaults: { _controller: ApidaeBundle:Default:rechercheSimple }
