services:
#    apidae.example:
#        class: ApidaeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    libelleLangue:
      class: ApidaeBundle\Twig\Extension\Fonctions
      tags:
        - { name: twig.extension }
