fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

profile:
    path: /{langueLocale}/consulterProfile
    defaults: { _controller: UserBundle:Default:voirProfil }

listeUsers:
    path: /{langueLocale}/admin/liste/utilisateurs
    defaults: { _controller: UserBundle:Default:listeUtilisateurs }

editionProfile:
    path: /editionProfile
    defaults: { _controller: FOSUserBundle:Profile:edit }

modifierUser:
    path: /admin/modifier/utilisateur/{userId}
    defaults: { _controller: UserBundle:Default:updateUtilisateur }
    methods: [POST, GET]

deleteUser:
    path: /admin/delete/utilisateur/{userId}
    defaults: { _controller: UserBundle:Default:deleteUser }

